### ISSUE TITLE
Alveo card support

### ISSUE THREAD

**Issue by mbrobbel** [abs-tudelft/fletcher#103]
This is a tracking issue for [Alveo](https://www.xilinx.com/products/boards-and-kits/alveo.html) card support in Fletcher.

It seems that there are currently three methods to develop for Alveo cards:
1. Using SDx + XRT. Primary development method as documented by Xilinx [here](https://www.xilinx.com/support/answers/71752.html).
1. Using SDx + XRT with custom RTL kernels developed in Vivado and packaged as a Xilinx Object File. Documented [here](https://www.xilinx.com/html_docs/xilinx2018_3/sdaccel_doc/creating-rtl-kernels-qnk1504034323350.html#qbh1504034323531), with an example [here](https://github.com/Xilinx/SDAccel_Examples/tree/master/getting_started/rtl_kernel/rtl_vadd).
1. Using Custom flow with Vivado Board Aware flow. Documented [here](https://www.xilinx.com/support/answers/71754.html). Board files for Vivado are available [here](https://github.com/Xilinx/XilinxBoardStore).

SDx development depends on XRT. In order to support SDx kernel development (development method 1 and 2) for Fletcher we need to provide a build target which generates the wrapping kernel for the accelerator and a platform runtime which wraps around XRT for execution. This method makes sense if Arrow has native or OpenCL kernel support.

Custom flow with Vivado (development method 3) makes more sense now but can't be used with XRT. Based on [this](https://forums.xilinx.com/t5/Alveo-Data-Center-Accelerator/QDMA-on-ALVEO-U200/td-p/966847) we can use QDMA with [this](https://www.xilinx.com/products/intellectual-property/pcie-qdma.html) ([Github](https://github.com/Xilinx/dma_ip_drivers)).

I'll investigate.

**Comment by johanpel** [comment]
Closing this as this will move to a separate repository: https://github.com/abs-tudelft/fletcher-alveo
