### ISSUE TITLE
IP-XACT frontend and backend for Cerata

### ISSUE THREAD

**Issue by mbrobbel** [abs-tudelft/fletcher#114]
The goal is to build a Cerata frontend and backend for [IP-XACT](https://en.wikipedia.org/wiki/IP-XACT).

The frontend should parse an IP-XACT package to Cerata graphs, and the backend should allow bundling Cerata graph's into an IP-XACT package.

More info on IP-XACT
[Info](https://www.accellera.org/downloads/standards/ip-xact)
[Schema's](http://www.accellera.org/XMLSchema/IPXACT/1685-2014/)
[User guide](https://www.accellera.org/images/downloads/standards/ip-xact/IP-XACT_User_Guide_2018-02-16.pdf)
[kactus2](http://funbase.cs.tut.fi/#ipxact)
[kactus2-code](https://github.com/kactus2/kactus2dev/tree/master/IPXACTmodels)

**Comment by johanpel** [comment]
Moved this here:
https://github.com/abs-tudelft/cerata/issues/4
