### ISSUE TITLE
Release build of Fletchgen is broken

### ISSUE THREAD

**Issue by mbrobbel** [abs-tudelft/fletcher#185]
While working on #181 I ran into the following bug:

**Describe the bug**
```
[INFO ]: Loading RecordBatch(es) from recordbatch.rb
[INFO ]: Creating SchemaSet.
[DEBUG]: Schema ExampleBatch, Direction: in
[INFO ]: Generating Mantle...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Not implemented.
```

**To Reproduce**
Make a release build of fletchgen and work through the tutorial.

**Expected behavior**
It should work like the debug build.

**Additional context**
Confirmed it's not a Cython side-effect by running a release build locally (this is macOS):
```
./fletchgen -n Sum -r recordbatch.rb                                                                  0.05s  11:44:20
[INFO ]: Loading RecordBatch(es) from recordbatch.rb
[INFO ]: Creating SchemaSet.
[DEBUG]: Schema ExampleBatch, Direction: in
[INFO ]: Generating Mantle...
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Not implemented.
```

**Comment by johanpel** [comment]
I've reproduced this with success. 

It seems that somehow the template specialization for T=int for this function:

`static std::shared_ptr<Literal> Make(T value)` on line 216 in node.h

is left out during release build. What dark magic is responsible for this I have no idea.
