### ISSUE TITLE
Pin all dependencies

### ISSUE THREAD

**Issue by mbrobbel** [abs-tudelft/fletcher#214]
We're still using some unpinned dependencies which may cause build failures due to upstream changes. We should make sure that all dependencies are pinned.

**Comment by johanpel** [comment]
With the exception of dependencies on: https://github.com/abs-tudelft/cmake-modules.git
there are currently no unpinned dependencies anymore.
Would you like to pin it on the latest commit there or would you like to create a tag @mbrobbel  ?

**Comment by mbrobbel** [comment]
> With the exception of dependencies on: https://github.com/abs-tudelft/cmake-modules.git
> there are currently no unpinned dependencies anymore.
> Would you like to pin it on the latest commit there or would you like to create a tag @mbrobbel ?

Pinning to the lastest commit is fine 👍

**Comment by johanpel** [comment]
You know what, let's just make an exception for cmake-modules, it's stable and rarely changes.
Saves us a bunch of commits if it ever does to fix a bug here or there.
Hence I can close this.
