### ISSUE TITLE
Will you run fletcher on aliyun F3 platform ?

### ISSUE THREAD

**Issue by yaoye-ali** [abs-tudelft/fletcher#286]
This is the platform :https://www.aliyun.com/product/ecs/fpga?spm=5176.12418109.aliyun-offcial-website-list-react.1.307729b36PzL2b

**Comment by johanpel** [comment]
As I'm not sure who you mean to ask this, I will answer: "Will Fletcher run on Aliyun F3?"

I would assume that it will, were someone to implement a platform library for it.
Fletcher is known to run on other UltraScale+ devices already, like the Xilinx Alveo cards and the AlphaData ADM-PCIE-9H7.

I can't read Chinese, but from the Google translate version of that page it seems like a platform similar to AWS EC2 F1?

If you would like to implement a platform implementation for it, you could take a look at the following link for inspiration:
https://github.com/abs-tudelft/fletcher-aws

Closing this assuming the question is answered.
