### ISSUE TITLE
Allow MMIO register write from user hardware in Fletchgen generated simulation

### ISSUE THREAD

**Issue by lars2309** [abs-tudelft/fletcher#71]
MMIO register writes by the user hardware are not propagated back to the register input in simulation top level.

`regs_in` : to user hardware
`regs_out` : from user hardware
`regs_out_en` : write enable signal from user hardware
`regs` : register state in simulation

`regs_out` is properly propagated to `regs`, but not to `regs_in`. This is not trivial, since the value of `regs_in` and `regs` are determined in separate processes.

Example with an additional write enable, and connecting `regs` instead of `regs_in` to the user hardware:
```
  regs_out_proc: process(acc_clk) is
  begin
    if rising_edge(acc_clk) then
      for I in 0 to NUM_REGS-1 loop
        if regs_out_en(I) = '1' then
          regs((I+1)*REG_WIDTH-1 downto I * REG_WIDTH) <= regs_out((I+1)*REG_WIDTH-1 downto I * REG_WIDTH);
        elsif regs_sim_we(I) = '1' then
          regs((I+1)*REG_WIDTH-1 downto I * REG_WIDTH) <= regs_in((I+1)*REG_WIDTH-1 downto I * REG_WIDTH);
        end if;
      end loop;
    end if;
  end process;
```

**Comment by johanpel** [comment]
Closing because new fletchgen in #98 
This method of reading/writing to/from mmio is not used anymore
