### ISSUE TITLE
StreamPipelineControl output FIFO is sometimes sized too small

### ISSUE THREAD

**Issue by jvanstraten** [abs-tudelft/fletcher#94]
In some cases, StreamPipelineControl seems to size its output FIFO smaller than the pipeline depth, resulting in (oscillating) backpressure. NUM_PIPE_REGS=2 and MIN_CYCLES_PER_TRANSFER=1 replicates the issue.

**Comment by johanpel** [comment]
Closing this as it is now part of https://github.com/abs-tudelft/vhlib

Copied to 
https://github.com/abs-tudelft/vhlib/issues/4
